authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),

]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/)', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    ]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shop/', include('mainapp.urls')),
    path('', mainapp.main, name='main'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('products_list/', mainapp.products_list, name='products_list'),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import title
import random
from basketapp.models import Basket
from .models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def main(request):
    title = 'главная'
    products = Product.objects.all()[:4]
    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)

'''def products(request, pk=None):
        title = 'продукты'
        links_menu = ProductCategory.objects.all()

        if pk is not None:
            if pk == 0:
                products = Product.objects.all().order_by('price')
                category = {'name': 'все'}
            else:
                category = get_object_or_404(ProductCategory, pk=pk)
                products = Product.objects.filter(category__pk=pk).order_by('price')

            content = {
                'title': title,
                'links_menu': links_menu,
                'category': category,
                'products': products,
            }

            return render(request, 'mainapp/products_list.html', content)

        same_products = Product.objects.all()[3:5]

        content = {
            'title': title,
            'links_menu': links_menu,
            'same_products': same_products
        }
        return render(request, 'mainapp/products.html', content)'''


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = getBasket(request.user)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True,
                                              category__is_active=True).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)


def contacts(requests):
    return render(requests, 'mainapp/contacts.html')


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)

def products_list(request, pk=None):
    basket = []
    links_menu = ProductCategory.objects.all()
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk:
        if pk == '0':
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products


def products(request, pk=None):
    title = 'продукты'
    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block menu %}

        {% endblock %}

        {% block content %}

        {% endblock %}

	</div>

    {% block footer %}
        <div class="footer">
            <div class="text-footer">
               <h3>контакты</h3>
            </div>
            <div class="text-footer">
               <h3>полезная информация</h3>
            </div>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/contacts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body class="container">
    <div class="topmenu">
        {% include 'mainapp/head_links.html' %}
    </div>

    <h2 class="h2class">Contact Us</h2>
    <p class="paragraph">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, ratione.</p>
    <img src="{% static 'img/funnycat.jpg' %}" width="350px" height="350px" alt="cat">
    <div class="contacts_and_form">
        <div class="contacts">
            <h4 class="h4class">Address</h4>
            <p class="paragraph">Lorem ipsum, dolor sit amet consectetur adipisicing.</p>
            <h4 class="h4class">Phone</h4>
            <ul>
                <li>+7445 3434 3445 34</li>
                <li>+743 3445 3434 23</li>
            </ul>
            <h4 class="h4class">Online service</h4>
            <ol>
                <li><a href="https://mail.ru/">Mail.ru</a> Телефон: +75454 344 3434</li>
                <li><a href="https://yandex.ru/">Yandex</a> Телефон: +7545 342 3455</li>
            </ol>
        </div>
        <div class="form_contacts">
            <h4 class="h4class">Send us message</h4>
            <form action="#">
                Full name: <input class="inpt-area" type="Full name" placeholder="John Silver"><br>
                Email: <input class="inpt-area" type="email" placeholder="email@mail.com"><br>
                Message: <textarea class="inpt-area" cols="30" rows="5"></textarea><br>
                <button class="button" type="submit">Швырнуть текст</button><br><br>
        </div>
    </div>
    <script type="text/javascript" charset="utf-8" async
        src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Afa51dfe1d1a573e966f34fbb891a5291b43e7c03d468f20be268a4881f576622&amp;width=1168&amp;height=664&amp;lang=ru_RU&amp;scroll=true"
        class="yandex_maps"></script>
    </form>
    Наши контакты: <br>
    <ol>
        <li>Наш верховный настоятель для первой коммуникации: +37 547885 342 . Email: nastoyatel@henso.ru</li>
        <li>Бухгалтерия для активных граждан для фин. вопросов: +45 34324 31255 . Email: buhgalteriya@henso.ru</li>
        <li>Отдел по работе со сложными клиентами и общественностью: + 65 343 2345532 . Email: hardclients@henso.ru</li>
    </ol>
    <form action="#">
        Вы также можете оставить свои контактные данные и подписаться на наш социальный канал: <br>
        Номер телефона: <input class="inpt-area" type="phone" placeholder="+79998887766"><br>
        Email: <input class="inpt-area" type="email" placeholder="mail@mail.com">
        <button class="button" type="submit">Подписаться</button>
        <button class="button" type="reset">Стересть данные в форме</button>
    </form>
    <p class="paragraph"><b>Все права защищены {% now "Y" %}</b> &copy;</p>
</body>

</html>

mainapp/templates/mainapp/head_links.html
{% load static %}
<a href="{% url 'main' %}" class="block_href1"><img src="{% static 'img/Circles.png' %}" alt="Main Page"></a>
<a href="{% url 'products:index' %}" class="block_href1"><img height="40px" width="40px" src="{% static 'img/shops.png' %}" alt="Shop"></a>
<a href="{% url 'contacts' %}" class="block_href2"><img src="{% static 'img/contacts.png' %}" alt="Contacts"></a>

mainapp/templates/mainapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>



<body>
    <div class="top">
        <div class="container top__box">
            <div class="topheader">
                <div class="header">
                    <div class="topmenu">
                        {% include 'mainapp/head_links.html' %}
                    </div>
                    <div class="lastheader">
                        <h1 class="h1class">New Automation
                            Tool for Your </h1>
                        <p class="paragraph p_h1_text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                            Est excepturi aliquam porro adipisci iusto velit veritatis laborum sequi perferendis, error
                            ipsum ipsam maxime omnis non laboriosam doloribus deserunt asperiores sit!</p>
                        <a href="#" class="see_project">See our project</a>
                    </div>

                </div>
            </div>
        </div>



        <div class="topmiddle what-we-do container">
            <h3 class="h3class">What we do to help our client grow in digital era
            </h3>
            <div class="middle">
                <div class="middledown">
                    <img class="img" src="{% static 'img/boy.png' %}" alt="boy">
                    <h4 class="h4class">Третий заголовок моей страницы с h4 и более 5ти словами</h4>
                    <p class="paragraph h4after_text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia
                        porro
                        eveniet
                        fugiat sed debitis error pariatur assumenda vero ea rerum iusto, commodi, labore nam quasi
                        officia!
                        Voluptates debitis doloribus ipsa.</p>
                    <a class="card" href="#">Learn more</a>
                </div>
                <div class="middledown">
                    <img class="img" src="{% static 'img/girl1.png' %}" alt="boy">
                    <h4 class="h4class">Третий заголовок моей страницы с h4 и более 5ти словами</h4>
                    <p class="paragraph h4after_text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia
                        porro
                        eveniet
                        fugiat sed debitis error pariatur assumenda vero ea rerum iusto, commodi, labore nam quasi
                        officia!
                        Voluptates debitis doloribus ipsa.</p>
                    <a class="card" href="#">Learn more</a>
                </div>
                <div class="middledown">
                    <img class="img" src="{% static 'img/girl2.png' %}" alt="boy">
                    <h4 class="h4class">Третий заголовок моей страницы с h4 и более 5ти словами</h4>
                    <p class="paragraph h4after_text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia
                        porro
                        eveniet
                        fugiat sed debitis error pariatur assumenda vero ea rerum iusto, commodi, labore nam quasi
                        officia!
                        Voluptates debitis doloribus ipsa.</p>
                    <a class="card" href="#">Learn more</a>
                </div>
            </div>
        </div>

        <div class="secondmiddle">
            <h3 class="h3class">Our Finished Project</h3>
            <p class="paragraph h3class_text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi sequi
                similique
                eveniet
                reprehenderit aperiam
                nihil atque enim maiores vel magni nemo porro id labore velit ratione libero, quis fuga doloremque?
            </p>
            <div class="project__item"><img class="project__img" src="{% static 'img/Mask1.png' %}" alt="mask1">
                <p class="project__text">Smart Home Intallation</p>
            </div>
            <div class="project__parent">
                <div class="project__item"><img class="project__img" src="{% static 'img/Mask2.png' %}" alt="mask2">
                    <p class="project__text2">Sparklite App</p>
                </div>
                <div class="project__item"><img class="project__img" src="{% static 'img/Mask3.png' %}" alt="mask3">
                    <p class="project__text3">Car-Rapetition App</p>
                </div>
            </div>
        </div>

        <div class="footer topbottom">
            <div class="container">
                <div class="bottomonemiddle">
                    <div class="bottomonedown">
                        <h3 class="h3class h3_footer"> Intersted to woek
                            with our team?</h3>
                        <p class="paragraph footer__afterh3">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                            Blanditiis,
                            fuga
                            quibusdam
                            consequatur
                            tempore ipsum
                            expedita, exercitationem inventore, dignissimos unde minima voluptatibus. Inventore
                            similique
                            saepe
                            incidunt
                            reiciendis neque molestiae assumenda mollitia.</p>
                    </div>
                    <div class="lets_talk">Let’s Talk</div>
                </div>
                <hr>

                <div class="bottomsecondmiddle">
                    <b class="list">Наши контакты:</b> <br>
                    <ol class="footer_list">
                        <li class="list">Наш верховный настоятель для первой коммуникации: +37 547885 342 . Email:
                            nastoyatel@henso.ru
                        </li>
                        <li class="list">Бухгалтерия для активных граждан для фин. вопросов: +45 34324 31255 .
                            Email:
                            buhgalteriya@henso.ru
                        </li>
                        <li class="list">Отдел по работе со сложными клиентами и общественностью: + 65 343 2345532 .
                            Email:
                            hardclients@henso.ru
                        </li>
                    </ol>
                    <form action="#" class="form__footer"> <br>
                        Вы также можете оставить свои контактные данные и подписаться на наш социальный канал: <br>
                        Номер телефона: <input class="inpt-area"><br>
                        Email: <input class="inpt-area" type="email" placeholder="mail@mail.com">
                        <button class="button" type="submit">Подписаться</button>
                        <button class="button" type="reset">Стереть данные в форме</button>
                        <div class="lessbottom">
                            <p class="paragraph footer__end"><b>Все права защищены {% now "Y" %} </b> &copy;</p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div>
            {% for product in products %}
              <div class="block">
                <a href="#">
                  <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                  <div class="text">
                    <h3>{{ product.category.name }}</h3>
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.description }}</p>
                  </div>
                </a>
              </div>
            {% endfor %}
        </div>
    </div>
</body>



</html>

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
      {% include 'mainapp/includes/inc_menu.html' %}
    </div>
  </div>
{% endblock %}

{{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>Категория: "{{ category.name|title }}"</h2>
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
              <
            </a>
          {% endif %}
          <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page' category.pk products.next_page_number %}">
              >
            </a>
          {% endif %}
        </div>
      </div>
      <div class="category-products clearfix">

        {% for product in products %}
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="product">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  <p>{{ product.description }}</p>
              </div>
            </a>
          </div>
        {% endfor %}

        <div class="category-products clearfix">
           {% for product in products %}
            <div class="block">
            <a href="{% url 'basket:add' product.pk %}">
            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
            <div class="text">
            <img src="{% static 'img/icon-hover.png' %}" alt="hover">
            <h4>{{ product.name }}</h4>
            <p>{{ product.description }} </p>
        </div>
      </a>
    </div>
  {% endfor %}
</div>


      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}